/* foobar is a creation of theylive, de nada */
var Bot = require('ttapi')
var repl = require('repl');;
global.foobar = Bot.prototype;
foobar.config = require('./config');
foobar.ready = require('./lib/ready.js');
foobar.change = require('./lib/change');
foobar.chat = require('./lib/chat');
foobar.$ = require('jquery');
foobar.mod = require('./lib/mod');
foobar.afk = require('./lib/afk');
foobar.signal = require('./lib/signal');
foobar.user = require('./lib/user');
foobar.boot = require('./lib/boot');
foobar.stage = require('./lib/stage');
foobar.song = require('./lib/song');
foobar.votes = require('./lib/votes');
foobar.end = require('./lib/end');
foobar.tweet = require('./lib/tweet');
foobar.queue = require('./lib/queue');
foobar.schlong = require('./lib/schlong');
foobar.rps = require('./lib/rps');
foobar.hump = require('./lib/hump');
foobar.spud = require('./lib/spud');
foobar.djbattle = require('./lib/battle');
foobar.nuke = require('./lib/nuke');
foobar.logs = require('./lib/log');
bot = new Bot(auth, botid, room);
repl.start('> ').context.bot = bot;
bot.on('ready', function(data){this.ready.get(data);});
bot.on('roomChanged', function (data){this.change.get(data);});
bot.on('speak', function (data){this.chat.cmds(data);});
bot.on('pmmed', function (data){this.chat.cmds(data);});
bot.on('registered', function (data){this.user.register(data);});
bot.on('deregistered', function (data){this.user.deregister(data);});
bot.on('newsong', function (data){this.song.get(data);});
bot.on('snagged', function (data){this.song.snagged(data);});
bot.on('update_votes', function (data){this.votes.get(data);});
bot.on('endsong', function (data){this.end.get(data);});
bot.on('add_dj', function (data){this.stage.get(data);});
bot.on('rem_dj', function (data){this.stage.give(data);});
bot.on('new_moderator', function (data){this.mod.get(data)});
bot.on('rem_moderator', function (data){this.mod.give(data)});