/* foobar is a creation of theylive, de nada */
var Bot = require('ttapi');
var repl = require('repl');
global.tweet = require('twit');
global.foobar = Bot.prototype;
global.config = require('../config');
global.base = require('./lib/base');
global.clever = require('./node_modules/cleverbot-node/lib/cleverbot');
foobar.$ = require('jQuery');
foobar.help = require('./lib/help');
foobar.system = require('./lib/system');
foobar.mod = require('./lib/mod');
foobar.chat = require('./lib/chat');
foobar.signal = require('./lib/signal');
foobar.stage = require('./lib/stage');
foobar.afk = require('./lib/afk');
foobar.queue = require('./lib/queue');
foobar.djbattle = require('./lib/battle');
foobar.nuke = require('./lib/nuke');
foobar.song = require('./lib/song');
foobar.games = require('./lib/games');
foobar.menu = require('./lib/menu');
bot = new Bot(auth, botid, room);
repl.start('> ').context.bot = bot;
bot.on('ready', function(data){this.system.ready(data);});
bot.on('roomChanged', function (data){this.system.change(data);});
bot.on('registered', function (data){this.system.register(data);});
bot.on('deregistered', function (data){this.system.deregister(data);});
bot.on('speak', function (data){this.chat.cmds(data);});
bot.on('pmmed', function (data){this.chat.cmds(data);});
bot.on('add_dj', function (data){this.stage.get(data);});
bot.on('rem_dj', function (data){this.stage.give(data);});
bot.on('newsong', function (data){this.song.new(data);});
bot.on('endsong', function (data){this.song.end(data);});
bot.on('snagged', function (data){this.song.snagged(data);});
bot.on('new_moderator', function (data){this.mod.get(data)});
bot.on('rem_moderator', function (data){this.mod.give(data)});
bot.on('update_votes', function (data){this.song.votes(data);});